name: icons_plus
description: The icons plus package offers a convenient collection of popular icon packs, including Bootstrap, Font Awesome, Eva Icons, Line Awesome, Ionicons, and many more.
version: 4.0.0
homepage: https://rahulchouhan.me
repository: https://github.com/chouhan-rahul/icons_plus

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  assets:
    - assets/flags/
    - assets/logos/

  fonts:
    - family: bootstrap
      fonts:
        - asset: assets/fonts/bootstrap.ttf
    - family: boxicons-logos
      fonts:
        - asset: assets/fonts/boxicons-logos.ttf
    - family: boxicons-regular
      fonts:
        - asset: assets/fonts/boxicons-regular.ttf
    - family: boxicons-solid
      fonts:
        - asset: assets/fonts/boxicons-solid.ttf
    - family: eva-fill
      fonts:
        - asset: assets/fonts/eva-fill.ttf
    - family: eva-outline
      fonts:
        - asset: assets/fonts/eva-outline.ttf
    - family: fontawesome-brands
      fonts:
        - asset: assets/fonts/fontawesome-brands.ttf
    - family: fontawesome-regular
      fonts:
        - asset: assets/fonts/fontawesome-regular.ttf
    - family: fontawesome-solid
      fonts:
        - asset: assets/fonts/fontawesome-solid.ttf
    - family: heroicons-solid
      fonts:
        - asset: assets/fonts/heroicons-solid.ttf
    - family: iconsax
      fonts:
        - asset: assets/fonts/iconsax.ttf
    - family: ionicons
      fonts:
        - asset: assets/fonts/ionicons.ttf
    - family: lineawesome
      fonts:
        - asset: assets/fonts/lineawesome.ttf
    - family: octicons
      fonts:
        - asset: assets/fonts/octicons.ttf
    - family: pixelarticons
      fonts:
        - asset: assets/fonts/pixelarticons.ttf
